### ISSUE TITLE
unified crime API for Oakland

### ISSUE THREAD

**Issue by connor11528** [openoakland/oakland-crime-by-beat#1]
hey merged these geojson files into [oakland-crime-api/server/data/beats](https://github.com/jasonshark/oakland-crime-api/tree/master/server/data/beats)

It's an express server for JSON. The good people at Stamen have built an API that as of November 6, 2014 serves nothing but headers for Oakland. Documentation that does not work: http://oakland.crimespotting.org/api

**Comment by rbelew** [comment]
hey Connor,

yup, this is in active progress.  i'm pushing all historical data
to an updated CrimeSpotting facility now, and it should be
operational RealSoonNow.  i expect what you're currently seeing at
http://oakland.crimespotting.org/api is some mix of old+new.

```
Rik
```
